# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 4.0  # Allow 2x the expected time
  allowed_goal_duration_margin: 0.5
  
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - panda_arm_controller
    - hand_controller

  panda_arm_controller:
    type: FollowJointTrajectory
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - panda_finger_joint1
    action_ns: gripper_cmd
    default: true